# Generated by Django 4.0.5 on 2022-06-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=20)),
                ('game_date', models.DateField()),
                ('game_time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('member', models.IntegerField()),
            ],
        ),
    ]
